facelift or the ubuntu build instructions
Still does not build for me, it consistelntly explodes with
```
/usr/bin/ld: CMakeFiles/owncloudResources.dir/loadresources.cpp.o: in function `load_rc()':
loadresources.cpp:(.text+0x9): undefined reference to `qInitResources_owncloudResources_translations()'
```
I am missing some resource files??